server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
spring:
  profiles:
    active: test
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    hk: #数据源1
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://172.16.5.24:3306/govhkhk?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true
      username: govhk
      password: govhk09PO
    sc: #数据源2
      enabled: true
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://172.16.5.24:3306/govhksc?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true
      username: govhk
      password: govhk09PO
    en: #数据源3
      enabled: true
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://172.16.5.24:3306/govhken?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true
      username: govhk
      password: govhk09PO
    druid:
      # 连接池的配置信息
      initial-size: 5
      min-idle: 5
      maxActive: 20
      maxWait: 60000 # 配置获取连接等待超时的时间
      timeBetweenEvictionRunsMillis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true  # 打开PSCache，并且指定每个连接上PSCache的大小
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow: 127.0.0.1,192.168.163.1
        # IP黑名单 (存在共同时，deny优先于allow)
        deny: 192.168.1.73
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: root
        # 登录密码
        login-password: root

  thymeleaf:
    #生产环境设置true
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    static-path-pattern: /static/**
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: static/**

#mybatis
mybatis:
  # 实体类
  type-aliases-package: com.xiaoi.south.manager.entity
  # mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  # 开启驼峰
  mapUnderscoreToCamelCase: true
  #打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#日志
logging:
  config: classpath:log/logback.xml
  path: /home/log/spring-boot-druid
  level:
    com.xiaoi.south.manager.dao: DEBUG
#CheckLink
checklink.url:  http://govhkpocr.demo.xiaoi.com/HKyztRobot/irobot/getCheckLine
#manager login url
manager.login.url: http://govhkpocm.demo.xiaoi.com/manager/clustermgr/login.jsp
#二开manager地址
manager.url: http://govhkpocm.demo.xiaoi.com/hkyztmgr/crawlerlink/
scheduling.enabled: true